RUN (772.852000): py "PythonSalesMan/main.py" BRANCHANDBOUND2 TestSalesman\Graf100_200_17.GR TestSalesman\Graf100_200_17.VIS Outputs\Graf100_200_17_SalesmanBranchAndBound2.TRK
Traceback (most recent call last):
  File "C:\Users\emmah\OneDrive\Escritorio\UNI\SEGON\2\DA\Salesman\GraphApplication\PythonSalesMan\main.py", line 26, in <module>
    graph.TestNIU(graph.NIUAlumne1)
  File "C:\Users\emmah\OneDrive\Escritorio\UNI\SEGON\2\DA\Salesman\GraphApplication\PythonSalesMan\graph.py", line 232, in TestNIU
    raise Exception('el NIU no correspon a un alumne', niu)
Exception: ('el NIU no correspon a un alumne', '1709896')
TOTAL TIME=0.171343
